language: scala
scala:
  - 2.11.7

install:
  # do install steps here
  - echo hello world

script:
  # do script steps here
  - sbt 'set credentials += Credentials("Artifactory Realm", "dronekit.artifactoryonline.com", System.getenv("ARTIFACTORY_USER"), System.getenv("ARTIFACTORY_PASSWORD"))' ++$TRAVIS_SCALA_VERSION test